### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by abb1991** [mpkono/prj-rev-bwfs-dasmoto#1]
Your HTML looks really solid. I like your consistent white spacing, indentation, and encapsulation through divs. It makes your code very readable!

I noticed you added ids and classes to your elements, when would you want to use one rather than the other?

**Comment by mpkono** [comment]
IDs are specific to a single element as far as I know. Classes are one generalized step up. My notes from the lessons say to "Style elements while using the lowest degree of specificity."
